# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Pub_time',
            field=models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
