# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0002_auto_20170803_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Abst',
            field=models.CharField(default='abst', max_length=256, verbose_name='\u6458\u8981'),
            preserve_default=False,
        ),
    ]
